### ISSUE TITLE
IMPLEMENTATION: MIABIS Star Model

### ISSUE THREAD

**Issue by CeciliaEngels** [MIABIS/miabis#18]
- RD-Connect
 - BBMRI-ERIC Directory
 - Biobank Graz?
 - BBMRI-ERIC Cohort?

https://drive.google.com/drive/folders/1etEfNqx0QDnTqJHoJ3j_gJACd7WAPacG

**Comment by niinae** [comment]
It is important to finish the ongoing discussion on how to express combinations of various categories - the proposals we have for data cubes implemented via star model.

**Comment by niinae** [comment]
Implemented in the Directory summer 2024
